import { useQuery } from '@tanstack/react-query';
import { FileBox, Calendar } from 'lucide-react';
import { artifactsApi } from '@/services/api';
import { format } from 'date-fns';

export default function Artifacts() {
  const { data, isLoading } = useQuery({
    queryKey: ['artifacts'],
    queryFn: () => artifactsApi.list(),
  });

  return (
    <div className="space-y-6 fade-in">
      <div>
        <h1 className="text-3xl font-bold gradient-text mb-2">Artifacts</h1>
        <p className="text-dark-400">
          View all artifacts generated by your scripts
        </p>
      </div>

      {isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[...Array(6)].map((_, i) => (
            <div key={i} className="card p-6 animate-pulse">
              <div className="h-4 bg-dark-700 rounded w-3/4 mb-3"></div>
              <div className="h-3 bg-dark-800 rounded w-full"></div>
            </div>
          ))}
        </div>
      ) : data?.results && data.results.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {data.results.map((artifact) => (
            <div key={artifact.objectId} className="card card-hover p-6">
              <div className="flex items-start gap-4 mb-4">
                <FileBox className="w-10 h-10 text-accent-500" />
                <div className="flex-1">
                  <h3 className="font-semibold text-dark-50 mb-1">
                    {artifact.name}
                  </h3>
                  <p className="text-xs text-dark-500">
                    {artifact.type.toUpperCase()}
                  </p>
                </div>
              </div>

              <div className="space-y-2 text-sm">
                <div className="flex justify-between text-dark-400">
                  <span>Size:</span>
                  <span className="font-mono">{artifact.size} bytes</span>
                </div>
                <div className="flex justify-between text-dark-400">
                  <span>Version:</span>
                  <span className="font-mono">v{artifact.scriptVersion}</span>
                </div>
              </div>

              <div className="mt-4 pt-4 border-t border-dark-700 flex items-center text-xs text-dark-500">
                <Calendar className="w-3 h-3 mr-1" />
                {format(new Date(artifact.createdAt), 'MMM d, yyyy')}
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="card p-12 text-center">
          <FileBox className="w-16 h-16 text-dark-600 mx-auto mb-4" />
          <h3 className="text-lg font-semibold text-dark-300 mb-2">
            No artifacts yet
          </h3>
          <p className="text-dark-500">
            Artifacts will appear here when scripts generate outputs
          </p>
        </div>
      )}
    </div>
  );
}
